version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: kantar-app
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    ports:
      - "4000"
    volumes:
      - ./:/var/www
    networks:
      - backend
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - backend

networks:
  backend: